### ISSUE TITLE
BFHL.def

### ISSUE THREAD

**Issue by ChaT0n** [Myrcon/Procon-1#179]
Info repeated 3 times, is it normal ?
Lines 68,69,70

<code>68/ procon.protected.weapons.add None "U_KnifeTrench" Secondary Melee

69/ procon.protected.weapons.add None "U_KnifeTrench" Secondary Melee

70/ procon.protected.weapons.add None "U_KnifeTrench" Secondary Melee
</code>

**Comment by MorpheusXAUT** [comment]
Hey ChaT0n,

thanks for the find, looks like the line has been duplicated by accident, most likely during copy-pasting new configs in (since the commits including those changes edited the lines above and below).
I'll remove the duplicates and push the new config to the repo, although it shouldn't affect the functionality of Procon or any of its plugins.

Thanks for the report!
